### PR TITLE
Merging Colin's changes with main repo

### PR DESCRIPTION
**Pull request by txm676**
Michael has transferred the main repo to me, and it is quite far behind your version

### CODE REVIEW

**Comment by mkborregaard** [comment]
LGTM. You guys have really moved this along!

**Comment by mkborregaard** [comment]
It looks a bit strange @txm676 that you're doing the PR from Colin to your fork, instead of @csgillespie opening this, but I guess that works as well :-)

**Comment by txm676** [comment]
@mkborregaard  this is less to do with efficiency and more to do with my very poor github knowledge :(

**Comment by csgillespie** [comment]
@txm676 Should be good to merge.

BTW, you should sign up for travis and codv (see the badges in the README)

**Comment by txm676** [comment]
@csgillespie great, thanks

I'm signed up for travis - seems to be checking it all now

**Comment by mkborregaard** [comment]
Looks like you gotta add rmarkdown install to your travis commands.

**Comment by txm676** [comment]
I've tried to add it but having some issues, will try again tomorrow.

**Pull request merged**
