### PR TITLE
Update to version 2.0

### PR DESCRIPTION
**Pull request by csgillespie**
No changes implemented regarding https://github.com/mkborregaard/gambin/issues/4

### CODE REVIEW

**Comment by mkborregaard** [comment]
Awesome – well done! And I know that I have been asking for this – but I am going on holiday today and will probably only be able to look this over in the New Year :-(
—
____________________________________
Michael Krabbe Borregaard, MSc, PhD
Assistant Professor (TT), Center for Macroecology, Evolution & Climate
Natural History Museum of Denmark, University of Copenhagen
Universitetsparken 15, DK-2100 Copenhagen

Subject Editor, Ecography
Associate Editor, Global Ecology and Biogeography

Featured paper:
Oceanic island biogeography through the lens of the general dynamic model: assessment and prospect<http://onlinelibrary.wiley.com/doi/10.1111/brv.12256/full>, Biological Reviews (2016).
An Anthropocene map of genetic diversity<http://science.sciencemag.org/content/353/6307/1532>, Science (2016)

Fra: Colin Gillespie <notifications@github.com<mailto:notifications@github.com>>
Svar til: mkborregaard/gambin <reply@reply.github.com<mailto:reply@reply.github.com>>
Dato: onsdag den 21. december 2016 kl. 12.48
Til: mkborregaard/gambin <gambin@noreply.github.com<mailto:gambin@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Emne: [mkborregaard/gambin] Update to version 2.0 (#5)


No changes implemented regarding #4<https://github.com/mkborregaard/gambin/issues/4>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mkborregaard/gambin/pull/5

Commit Summary

  *   Switch to Rmd for README
  *   Update ignore.
  *   Bump version
  *   Moved over to roxygen2
  *   Update dgambin to match standard d* functions
  *   Add p/q/r gambin function
  *   Add NEWS file
  *   Remove non-standard dots for function names.
  *   Changed odd if statement
  *   Removed nesting from if statements
  *   Code spacing
  *   Update to use new dgambin function
  *   Minor docs
  *   Simplify code
  *   Empty file
  *   Change plot to barplot. Add in lines and points
  *   Missing args
  *   Formatting
  *   Typo in travis URL
  *   Obsolete arguments
  *   Formatting
  *   Update authors list with person.
  *   Bump NAMESPACE.
  *   Add travis file
  *   Initial vignette.
  *   Adding initial testthat
  *   Adding vignette builder (knitr)
  *   Ignore travis file when building
  *   Bump version and NEWS
  *   Get df.
  *   Spacing
  *   Use diff instead of minus
  *   Switch from gambin2 to gambin.
  *   Change URLs to mkborregaard

File Changes

  *   A .Rbuildignore<https://github.com/mkborregaard/gambin/pull/5/files#diff-0> (5)
  *   A .gitignore<https://github.com/mkborregaard/gambin/pull/5/files#diff-1> (4)
  *   A .travis.yml<https://github.com/mkborregaard/gambin/pull/5/files#diff-2> (19)
  *   M DESCRIPTION<https://github.com/mkborregaard/gambin/pull/5/files#diff-3> (30)
  *   M NAMESPACE<https://github.com/mkborregaard/gambin/pull/5/files#diff-4> (50)
  *   A NEWS.md<https://github.com/mkborregaard/gambin/pull/5/files#diff-5> (18)
  *   D R/AIC.gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-6> (7)
  *   M R/AICc.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-7> (25)
  *   D R/AICc.gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-8> (11)
  *   R R/BIC_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-9> (6)
  *   D R/confint.gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-10> (6)
  *   A R/confint_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-11> (19)
  *   M R/create_octaves.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-12> (35)
  *   A R/data_docs.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-13> (8)
  *   M R/dgambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-14> (131)
  *   D R/fitGambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-15> (53)
  *   A R/fit_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-16> (77)
  *   D R/gambin-internal.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-17> (33)
  *   A R/gambin-package.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-18> (32)
  *   M R/gambin_exp.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-19> (9)
  *   D R/logLik.gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-20> (5)
  *   A R/logLik_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-21> (29)
  *   R R/nobs_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-22> (2)
  *   D R/plot.gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-23> (9)
  *   A R/plot_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-24> (28)
  *   R R/predict_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-25> (1)
  *   R R/print_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-26> (1)
  *   R R/print_summary_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-27> (7)
  *   R R/summary_gambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-28> (1)
  *   A README.Rmd<https://github.com/mkborregaard/gambin/pull/5/files#diff-29> (37)
  *   M README.md<https://github.com/mkborregaard/gambin/pull/5/files#diff-30> (28)
  *   M gambin.Rproj<https://github.com/mkborregaard/gambin/pull/5/files#diff-31> (1)
  *   M man/create_octaves.Rd<https://github.com/mkborregaard/gambin/pull/5/files#diff-32> (39)
  *   M man/dgambin.Rd<https://github.com/mkborregaard/gambin/pull/5/files#diff-33> (74)
  *   M man/fitGambin.Rd<https://github.com/mkborregaard/gambin/pull/5/files#diff-34> (84)
  *   M man/gambin-package.Rd<https://github.com/mkborregaard/gambin/pull/5/files#diff-35> (58)
  *   M man/logLik.gambin.Rd<https://github.com/mkborregaard/gambin/pull/5/files#diff-36> (45)
  *   M man/moths.Rd<https://github.com/mkborregaard/gambin/pull/5/files#diff-37> (26)
  *   A tests/testthat.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-38> (2)
  *   A tests/testthat/testing_dgambin.R<https://github.com/mkborregaard/gambin/pull/5/files#diff-39> (8)
  *   A vignettes/overview.Rmd<https://github.com/mkborregaard/gambin/pull/5/files#diff-40> (38)
  *   A vignettes/refs.bib<https://github.com/mkborregaard/gambin/pull/5/files#diff-41> (22)

Patch Links:

  *   https://github.com/mkborregaard/gambin/pull/5.patch
  *   https://github.com/mkborregaard/gambin/pull/5.diff

**Comment by csgillespie** [comment]
That's OK; I'm on holiday tomorrow and just wanted to pass the buck ;)

**Comment by txm676** [comment]
Ok so I've just merged the 2.0 version (hopefully)

**Comment by mkborregaard** [comment]
Thanks for your amazing work on this, @csgillespie !

**Pull request merged**
